language: node_js
node_js:
- node
addons:
  sonarcloud:
    organization: "arnaud512-github"
    token: "oGJmOuGG+v01C7ZpeDPeI6AuXc1JTKDTYQ9Y9mrBdXTVkcUAetfvg7FyNVKd9j0z3VCA0w51nBfIXpP8cMQnwtlExTZ50V/m2xwLlI6ffs8Vu5LpNOpGzUrvnPeFbX4tIO24aTUqz2pE3w8cZQvn/F72+wTsznrCOE0h8+oSteExvEqb3r5xtb3BH5DsIiAdpZeYUz9iWbPuy/gZ8synAfqGDqy5IacySAFY4K0tVW4SObddEJP54+a2b/AsNe8+PyUcCIDR0RkJz5hFAPXHKzSWCtDbiJ2kUskvntN6FNvtf3yiN7k8lNk6JQyvYagrCglwsXkl3nifMC74D/0/TvI6d1vwgoDB1XJcFBTq1gdAIFG4VywJ0yQG9sXxg+5t4Iq1egqwE/szp1Wlsfu202maXjnUMAFtWwC3ghFAmsS4JQgVHf5d6ounHxVd+BuZYJ7ciDiS0tod3SGtMa0zJrRG7JnpRhBfzP2xrpKqX0UdXQWfxwsxcQHsXLy3XR6dngiVuENTTIGeEvb2dJ+Z0NXazbCVI1noDRFwPomethkf8LZ10eWHSyI007bsysilDFYdA+4hr+ir7lZ+qN/vpn+4gvsB1pTreQNejfWhv8lSBePcog9E5sjy8kYMOpbBmz9fb6zcPvEfQ1ux7ZgHJQugGD7mK0IilDtMiBhjK8k="
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- ng build --prod
- sonar-scanner -X
