language: node_js
node_js:
- node
addons:
  sonarcloud:
    organization: "arnaud512-github"
    token:
      secure: "k2uDQJdyuxehdxyuZM5ChWIzQ1tYMbZmaz4JTCdtRQNFwJVHtt8yFIDM/tVrvuQ4luvBUb8Y8W9pPwKIQMpLKl0WjKvKaFPwlevHRbEkTG6T+7NKgHc7toswfCHBc9bMuzoF8IZ0bUDtS3Lt3EL+nVtcHN+wAH0T4uVd/bfwbDc3mzl5eOhZgiq7yHWKHlsFgmAYFo0b6ydm+hYEVVy05O+uNvU3vsoC78HoEijUy1nUi/Nl22RSVlfECcsqw0lfa29Cqzs1+Uf/+5VP7oRrG04bFak/mu4c45AiGVJNV9bOHffD4TUS8UIDInlrIe5B5al8TqCNZI3YjGE4IEClywet35XNyxy7y8q7CDwzMHQy4n0fEAi3eYdbm9tOlEijzZ5OEJ0AiYCMq6vo9r1p1mDJJjVWmK+Cgc0gUNKP4SKXWZpBiOu6f8ZlUrHsuhIUikPK5cR4GZYMC1A5TMhfSCtd+g1aH7o+y8gO1HXOSYi7xI3U2/pk1YLbvrH32+kxDsQke4O9cmaQkDb08c8XfeflHRPd71PcS7ELMQ3DFSoemV0RkvL+1u6uSRHwvPWgq5i+cVzvyifE1aaVitomurS2HHzOC5NfY9eD24PsJIljfBYN1TDr8xTdbtrMAVjeVs/o+Nk58MFhr1XfacthB9rS+NeQ1BQkAdeQ+kKZN+s="
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- ng build --prod
- sonar-scanner -X
