language: node_js
node_js:
- node
addons:
  sonarcloud:
    organization: "arnaud512-github"
    token:
      secure: "ZEY5LyVwtvDnUdioMNzuN12KO/EdELqYzqj7KyCF6liX+ORaU++8PRe6ciqcal3e7rd4T6AjyKrqMB4ODycn80+Zl1x1HW4gpNrIX2KA36Eg+51OLYVbvHpRAfDciE7+1mZTNASYQ8aB+AxgKSF1KuZItrXBSeR8Jluzrz5urSP/Phty1jZMYE1gRsQgSuvrLF22Ggx6ExnQkKsfJX+JtPg02W2c2jF3AS5kCq0bjychvnvA3hIyCQXEGAcJjX0072o9W4MD1MeA+i0/NsPFhWxrHJgRHYxLUxBwwiT//ZTL/TtjqGEHYNz8v2pbq/ZYTtBFssb91TPFkl4Q8S7I8hd1pm0UNTaJ1uJmGPypGGkCkXVimkeuuf+FY50+mdBjOqpaVkxLxgrBrxNKyxk4Q1M9N34InqLzp2ugrCbIeqgA9B2NN1WElA+FwcOhHHG0n+fYXWlWCDueDe4Xh4AUcVJRJ0O5MZ0f2dt8OauGiE7nw5yRiot59z0er405P6rXzDgSbYhdl2x6JpFNLT/4zDo3LmbkS+YR2hOFkMWfwHkTFf6Q/ye8WAWscq+B7H6fA9ywl2i1P4q4ukb5TeqWzpqzC18tLzXKhJQhhzAFBy3rrsiUpPWf7tXnQNVnbpLvTlPE2uibzCRg6obTPN/ZXrp/CvUuDqedFCv7TV7Kj8o="
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- ng build --prod
- sonar-scanner -X
