language: node_js
node_js:
- node
addons:
  sonarcloud:
    organization: "arnaud512-github"
    token:
      secure: AdGp8hyVcWQ1qPWEyzMAplI0Ay4tdPH9aGndNsH2ansDiBCjCUUi08QkEM3gn/eCylezMWKzHjLUHOnbEiO7zQfSxxsNAvOMbJL8W50R8a8WAxKAIfYSaGywqxtF9N8HMYgQNGXXY6PHBFJVG2vrh6YfmL5lpU9Qg02jqX0KkaaxcE1lu0unwMZS/NZMIlAt5QNLZh//Aps9/I4YNiPEdeUbMjpk89xYHqOfw24zSdLe9lSxblczMxnTERXNbcvy7JliDiPlhtnQB+d9hUd+YyLQlhEmARNCXxtclr4i0yrdlZoddYaiRWJvuIrtdMd7R536joOAHC/UzJ0fqz2q4/7B5CAXkn7HK9mp64NqYI8T6nuMmeTfRXQkHqeTcI0ApRPgNTFWRpvOBsBpHdCQpUC3xE9XsrR0AwvgdgHLpVp95zly4g1DFrzfqXgs6e4qnT1qET6y+zqf8OK/7VW0iXBi7LC4YfxvpIQg5Na1EXhJFw+0Cubl6TwyA60pLb5wSi3mDyF1iC9omuSrXO6ubNmPntaNA21cPw9LkqD3sSz6FjASvQNP1foTGoZNHJ+phsLBxaI3pHgrBP7Hie/WFI1iqy7CIPztc38ojYA1gQF7YqpGUchIUT8T7wWWTajI3BQ7NeDvKubINUpCFkjWwmW4Y6FEX4uznZrCbxCuwx8=
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- ng build --prod
- sonar-scanner
